//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_VendingMachine.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int id { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public string creator_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
