//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendingMachines.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_VendingMachinesEntities : DbContext
    {
        public DB_VendingMachinesEntities()
            : base("name=DB_VendingMachinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<CriticalThresholdTemplate> CriticalThresholdTemplate { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Events_VM> Events_VM { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<ModelsMachine> ModelsMachine { get; set; }
        public virtual DbSet<NotificationTemplates> NotificationTemplates { get; set; }
        public virtual DbSet<Operators> Operators { get; set; }
        public virtual DbSet<PaymentTypes> PaymentTypes { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<ServicePriorities> ServicePriorities { get; set; }
        public virtual DbSet<SettingTypes> SettingTypes { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Timezones> Timezones { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VendingMachines> VendingMachines { get; set; }
        public virtual DbSet<WorkModes> WorkModes { get; set; }
    }
}
