//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendingMachines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime end_date { get; set; }
        public bool is_accept { get; set; }
        public string user_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
