//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendingMachines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events_VM
    {
        public string id_vm { get; set; }
        public int id_event { get; set; }
        public System.DateTime last_date { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual VendingMachines VendingMachines { get; set; }
    }
}
