//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendingMachines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string issues_found { get; set; }
        public string vending_machine_id { get; set; }
        public string id_employee { get; set; }
        public string work_description { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual VendingMachines VendingMachines { get; set; }
    }
}
