//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendingMachines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int id { get; set; }
        public string product_id { get; set; }
        public string quantity { get; set; }
        public double total_price { get; set; }
        public System.DateTime timestamp { get; set; }
        public int payment_method { get; set; }
    
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual Products Products { get; set; }
    }
}
