//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendingMachines.Models
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;

    public partial class VendingMachines
    {
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendingMachines()
        {
            this.Events_VM = new HashSet<Events_VM>();
            this.Maintenance = new HashSet<Maintenance>();
            this.Products = new HashSet<Products>();
            this.SettingTypes = new HashSet<SettingTypes>();
            this.PaymentTypes = new HashSet<PaymentTypes>();
        }

        public string id { get; set; }
        public string name { get; set; }
        public int company { get; set; }
        public int model { get; set; }
        public int work_mode { get; set; }
        public string location { get; set; }
        public string place { get; set; }
        public string coordinates { get; set; }
        public string serial_number { get; set; }
        public string working_hours { get; set; }
        public Nullable<int> timezone { get; set; }
        public Nullable<int> matrix { get; set; }
        public Nullable<int> critical_threshold_template { get; set; }
        public Nullable<int> notification_template { get; set; }
        public string user_id { get; set; }
        public Nullable<int> @operator { get; set; }
        public string rfid_service { get; set; }
        public string rfid_cash_collection { get; set; }
        public string rfid_loading { get; set; }
        public string kit_online_id { get; set; }
        public Nullable<int> service_priority { get; set; }
        public string notes { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public Nullable<System.DateTime> last_maintenance_date { get; set; }
        public Nullable<double> total_income { get; set; }
        public string manager { get; set; }
        public string engineer { get; set; }
        public string technician { get; set; }
        public Nullable<int> monets { get; set; }
        public Nullable<int> kopurs { get; set; }
        public Nullable<int> sdacha { get; set; }
    
        
        public virtual Companies Companies { get; set; }
        public virtual ModelsMachine ModelsMachine { get; set; }
		public virtual CriticalThresholdTemplate CriticalThresholdTemplate { get; set; }
		public virtual Statuses Statuses { get; set; }
		public virtual NotificationTemplates NotificationTemplates { get; set; }
		public virtual ServicePriorities ServicePriorities { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
		public virtual ICollection<Events_VM> Events_VM { get; set; }

		[JsonIgnore]
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Maintenance> Maintenance { get; set; }

		public virtual Operators Operators { get; set; }

        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
		public virtual ICollection<Products> Products { get; set; }

		public virtual Timezones Timezones { get; set; }

		[JsonIgnore]
		public virtual Users Users { get; set; }

		[JsonIgnore]
		public virtual Users Users1 { get; set; }

		[JsonIgnore]
		public virtual Users Users2 { get; set; }

		[JsonIgnore]
		public virtual Users Users3 { get; set; }

		public virtual WorkModes WorkModes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		[JsonIgnore]
		public virtual ICollection<SettingTypes> SettingTypes { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		[JsonIgnore]
		public virtual ICollection<PaymentTypes> PaymentTypes { get; set; }
    }
}
